-- MySQL Script generated by MySQL Workbench
-- Wed Feb  8 21:49:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema uah_mad_g5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uah_mad_g5` ;

-- -----------------------------------------------------
-- Schema uah_mad_g5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uah_mad_g5` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `uah_mad_g5` ;

-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_circuito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_circuito` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_circuito` (
  `circuitoId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `ciudad` VARCHAR(150) NOT NULL,
  `pais` VARCHAR(150) NULL DEFAULT NULL,
  `trazado` VARCHAR(150) NULL DEFAULT NULL,
  `numeroVueltas` INT NOT NULL DEFAULT '0',
  `longitud` DOUBLE NOT NULL DEFAULT '0',
  `curvasLentas` INT NOT NULL DEFAULT '0',
  `curvasMedia` INT NOT NULL DEFAULT '0',
  `curvasRapidas` INT NOT NULL DEFAULT '0',
  `foto` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`circuitoId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_carrera` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `circuitoId` INT NOT NULL,
  `imagen` LONGTEXT NULL DEFAULT NULL,
  `nombre` VARCHAR(150) NULL DEFAULT NULL,
  `foto` LONGTEXT  NULL DEFAULT NULL,
  PRIMARY KEY (`idCarrera`),
  INDEX `fk_carrera_circuito_idx` (`circuitoId` ASC) VISIBLE,
  CONSTRAINT `fk_carrera_circuito`
    FOREIGN KEY (`circuitoId`)
    REFERENCES `uah_mad_g5`.`tbl_circuito` (`circuitoId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_equipo` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `logo` LONGTEXT NULL DEFAULT NULL,
  `logoGrande` LONGTEXT NULL DEFAULT NULL,
  `twitter` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `base` VARCHAR(50) NULL DEFAULT NULL,
  `Team_Chief` VARCHAR(50) NULL DEFAULT NULL,
  `Tech_Chief` VARCHAR(50) NULL DEFAULT NULL,
  `portada` LONGTEXT NULL DEFAULT NULL,
  `bandera` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idEquipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_piloto` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_piloto` (
  `idPiloto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(150) NOT NULL,
  `siglas` VARCHAR(45) NULL DEFAULT NULL,
  `dorsal` VARCHAR(45) NULL DEFAULT NULL,
  `foto` LONGTEXT NULL DEFAULT NULL,
  `pais` VARCHAR(120) NULL DEFAULT NULL,
  `twitter` VARCHAR(45) NULL DEFAULT NULL,
  `idEquipo` INT NOT NULL,
  `bandera` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idPiloto`),
  INDEX `fk_piloto_equipo_idx` (`idEquipo` ASC) VISIBLE,
  CONSTRAINT `fk_piloto_equipo`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `uah_mad_g5`.`tbl_equipo` (`idEquipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_carrera_piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_carrera_piloto` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_carrera_piloto` (
  `idCarreraPiloto` INT NOT NULL AUTO_INCREMENT,
  `idCarrera` INT NOT NULL,
  `idPiloto` INT NOT NULL,
  PRIMARY KEY (`idCarreraPiloto`),
  INDEX `fk_carrera_idx` (`idCarrera` ASC) VISIBLE,
  INDEX `fk_piloto_idx` (`idPiloto` ASC) VISIBLE,
  CONSTRAINT `fk_cp_carrera`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `uah_mad_g5`.`tbl_carrera` (`idCarrera`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cp_piloto`
    FOREIGN KEY (`idPiloto`)
    REFERENCES `uah_mad_g5`.`tbl_piloto` (`idPiloto`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_coche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_coche` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_coche` (
  `idCoche` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `codigo` VARCHAR(255) NOT NULL,
  `ersCurvaLenta` DOUBLE NULL DEFAULT NULL,
  `ersCurvaMedia` DOUBLE NULL DEFAULT NULL,
  `ersCurvaRapida` DOUBLE NULL DEFAULT NULL,
  `consumo` DOUBLE NULL DEFAULT NULL,
  `idEquipo` INT NULL DEFAULT NULL,
  `foto` LONGTEXT NOT NULL,
  PRIMARY KEY (`idCoche`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_rol` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(50) NOT NULL,
  `idRol` INT NOT NULL,
  `idEquipo` INT NULL,
  `definitivo` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_rol_idx` (`idRol` ASC) VISIBLE,
  INDEX `fk_usuario_equipo_idx` (`idEquipo` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `uah_mad_g5`.`tbl_rol` (`idRol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_equipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_equipo_usuario` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_equipo_usuario` (
  `idEquipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `idEquipo` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEquipoUsuario`),
  INDEX `fk_eu_equipo_idx` (`idEquipo` ASC) VISIBLE,
  INDEX `fk_eu_usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_eu_equipo`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `uah_mad_g5`.`tbl_equipo` (`idEquipo`),
  CONSTRAINT `fk_eu_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `uah_mad_g5`.`tbl_usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_noticia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_noticia` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_noticia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permalink` VARCHAR(250) NULL DEFAULT NULL,
  `titulo` VARCHAR(150) NOT NULL,
  `imagen` LONGTEXT NULL DEFAULT NULL,
  `idUsuario` INT NOT NULL,
  `texto` LONGTEXT NOT NULL,
  PRIMARY KEY (`idNoticia`),
  INDEX `fk_noticia_usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_noticia_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `uah_mad_g5`.`tbl_usuario` (`idUsuario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_votacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_votacion` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_votacion` (
  `idVotacion` INT NOT NULL AUTO_INCREMENT,
  `permalink` VARCHAR(250) NOT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaCulminacion` DATE NOT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idVotacion`),
  INDEX `fk_votacion_usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_votacion_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `uah_mad_g5`.`tbl_usuario` (`idUsuario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_votacion_piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_votacion_piloto` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_votacion_piloto` (
  `idVotacionPiloto` INT NOT NULL AUTO_INCREMENT,
  `idVotacion` INT NOT NULL,
  `idPiloto` INT NOT NULL,
  PRIMARY KEY (`idVotacionPiloto`),
  INDEX `fk_votacion_votacion_idx` (`idVotacion` ASC) VISIBLE,
  INDEX `fk_votacion_piloto_idx` (`idPiloto` ASC) VISIBLE,
  CONSTRAINT `fk_votacion_piloto`
    FOREIGN KEY (`idPiloto`)
    REFERENCES `uah_mad_g5`.`tbl_piloto` (`idPiloto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votacion_votacion`
    FOREIGN KEY (`idVotacion`)
    REFERENCES `uah_mad_g5`.`tbl_votacion` (`idVotacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `uah_mad_g5`.`tbl_voto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uah_mad_g5`.`tbl_voto` ;

CREATE TABLE IF NOT EXISTS `uah_mad_g5`.`tbl_voto` (
  `idVoto` INT NOT NULL AUTO_INCREMENT,
  `idVotacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `idPiloto` INT NOT NULL,
  PRIMARY KEY (`idVoto`),
  INDEX `fk_voto_votacion_idx` (`idVotacion` ASC) VISIBLE,
  CONSTRAINT `fk_voto_votacion`
    FOREIGN KEY (`idVotacion`)
    REFERENCES `uah_mad_g5`.`tbl_votacion` (`idVotacion`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
